# This is a basic workflow to help you get started with Actions

# Referência:
# https://betterprogramming.pub/how-to-version-your-code-in-2020-60bdd221278b

name: Bump version

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main
#   pull_request:
#     branches:
#       - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # Vide: https://github.com/actions/checkout/issues/317#issuecomment-737107262
      - uses: actions/checkout@v2
#         with:
#           ref: ${{ github.event.pull_request.head.ref }}

      # Runs a set of commands using the runners shell
      - name: Bump version
        run: |
          git config --global user.email "github+actions@gmail.com"
          git config --global user.name "Github Action"
          git fetch --tags

          # Get the latest version from GitHub tags
          OLD_VERSION=$(git tag --sort=-v:refname --list "v[0-9]*" | head -n 1 | cut -c 2-)
          NEW_VERSION=$(docker run --rm -v "$PWD":/app treeder/bump --input "$OLD_VERSION" patch)
          echo "New version: $NEW_VERSION"

          # Bump version in galaxy.yml
          docker run --rm -v "$PWD":/app treeder/bump --filename galaxy.yml --replace "$NEW_VERSION"

          # Push new version
          wget -O - https://raw.githubusercontent.com/treeder/bump/master/gitbump.sh | bash
